### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by ricknjacky** [sugarlabs/musicblocks-lib#10]
The dockerfile doesn't build instead, shows an error upon execution of docker build command.

![Screenshot (522)](https://user-images.githubusercontent.com/50985033/105695137-bcc01400-5f27-11eb-8ddb-8a8c69accdc6.png)

The dockerfile on my system:-
![image](https://user-images.githubusercontent.com/50985033/105695390-0dd00800-5f28-11eb-8e07-6b8c935f236e.png)

If I have done something wrong somewhere or I missed out on something crucial, please do tell me the same. I look forward to a fix for this issue. Thanks

**Comment by meganindya** [comment]
I tried a fresh build. Worked fine on my end `Docker version 20.10.2, build 2291f61`.
Try cleaning up unused images on your local system.

**Comment by ricknjacky** [comment]
Thanks for the feedback, the error was due to the new `buildkit` update [source](https://github.com/docker/buildx/issues/410)
I have fixed the issue. Closing this. Thanks again :)
